version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:  
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
      - MYSQL_DATABASE=main
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    driver: local